{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-cpgr
  version: 0.0.0.9000

source:
  git_url: https://github.com/populationgenomics/cpgr
  git_tag: main

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0
  noarch: generic

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}filesystem        # [win]
    - {{posix}}git
    - {{posix}}zip               # [win]

  host:
    - r-base
    - r-assertthat
    - r-dplyr
    - r-ggplot2
    - r-jsonlite
    - r-purrr
    - r-readr
    - r-rlang
    - r-stringr
    - r-tidyr

  run:
    - r-base
    - r-assertthat
    - r-dplyr
    - r-ggplot2
    - r-jsonlite
    - r-purrr
    - r-readr
    - r-rlang
    - r-stringr
    - r-tidyr

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('cpgr')"           # [not win]
    - "\"%R%\" -e \"library('cpgr')\""  # [win]


about:
  home: https://github.com/populationgenomics/cpgr
  license: MIT + file LICENSE
  summary: Centre for Population Genomics R utils and RMarkdown notebooks
  license_family: MIT
