name: conda-pkgdown

on:
  push:
    branches:
      - main

jobs:
  build-conda-deploy-pkgdown:
    if: "startsWith(github.event.head_commit.message, 'Bump version:')"
    name: Build conda package & deploy pkgdown website
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          # Do everything inside the base env
          auto-update-conda: true
          auto-activate-base: true
          activate-environment: ""
          mamba-version: "*"
          channels: "cpg,conda-forge,bioconda"

      - name: Conda package build and upload
        shell: bash -l {0}
        run: |
          mamba install conda-build conda-verify anaconda-client
          mamba build --R 4.1 deploy/conda-recipe/
          PKG_PATH="${CONDA_PREFIX}/conda-bld/**/*.tar.bz2"
          anaconda -t ${{ secrets.ANACONDA_UPLOAD_TOKEN }} upload --force $PKG_PATH

      - name: Install conda packages
        shell: bash -l {0}
        run: mamba env create -n pkgdown_cpgr -f deploy/pkgdown_conda_env.yaml

      - name: Publish pkgdown website
        shell: bash -l {0}
        run: |
            git config --local user.email "actions@github.com"
            git config --local user.name "GitHub Actions"
            conda activate pkgdown_cpgr
            printf "cpgr version:\n"
            Rscript -e "packageVersion('cpgr')"
            Rscript -e "pkgdown::deploy_to_branch(pkg = '.', commit_message = paste(pkgdown:::construct_commit_message('.'), '- see https://populationgenomics.github.io/cpgr/'), branch = 'gh-pages', new_process = FALSE)"
